### ISSUE TITLE
Nefunkčný modul

### ISSUE THREAD

**Issue by denkz0ne** [Adman/MMM-imhdsk#1]
Po zmene api na imhd.sk zrejme prestal pracovat aj tento modul. Dá sa to opraviť?

**Comment by Adman** [comment]
Urcite, akurat teraz aktualne nemam na to moc casu, niekedy sa na to snad pozriem.

**Comment by Adman** [comment]
Toto bude treba pravdepodobne fixnut v mojej kniznici https://github.com/Adman/node-imhdsk

**Comment by Adman** [comment]
Fixol som to, skus si stiahnut novu verziu.

**Comment by denkz0ne** [comment]
modul updatnuty, node-imhd tiez, funguje.. ale neberie mi povodne stop-id, nove neviem zistit. resp nefunguje pre moju zastavku(povodne je 278, miu p. biskupice). asi sa bude treba pozriet aj na sposob ziskavania stop-id. vyzera to tak ze data budu mat inu strukturu alebo co :D

**Comment by Adman** [comment]
248 by malo byt MiU P. Biskupice po novom.
