### ISSUE TITLE
Documentation lack

### ISSUE THREAD

**Issue by snipiba** [Adman/MMM-imhdsk#3]
Update docs with informations how and where to get stopId (url, or provide JSON data or something)

**Comment by Adman** [comment]
Thanks for the issue. I have to check whether this plugin still works and then update the docs.

**Comment by Adman** [comment]
@snipiba Hello, README has been updated, so I believe it's now clear how to get the stopID parameter. I also had to make some small fixes to the parser, which should be working now.

edit: https://github.com/Adman/MMM-imhdsk#finding-the-stop-id

**Comment by snipiba** [comment]
Great...
